### ISSUE TITLE
client: prices are not being stored in config db

### ISSUE THREAD

**Issue by eprueves** [facebookincubator/CommunityCellularManager#10]
In client/core/checkin.py, price configs are processed by calling 
`process_prices(self.conf, config_dict['prices'])` (line 87)

However, the arguments does not comply with the ordering defined in client/core/billing.py (line 227) 
`def process_prices(pricing_data, config_db):`.

As such, the endaga_config table does not get populated with the pricing data

**Comment by 9muir** [comment]
Good catch. We can easily fix this, but PRs are always welcome.

**Comment by 9muir** [comment]
resolved by PR #12, thank you
