### ISSUE TITLE
Cloud: settings.py file missing in clean install

### ISSUE THREAD

**Issue by infrared0** [facebookincubator/CommunityCellularManager#11]
From a fresh clone of this repository and setup of the Vagrant cloud vms: In the web vm virtual environment, python can't find the settings.py file, so makemigrations in manage.py fails with the following message:
File "/home/vagrant/cloud/endagaweb/settings/base.py", line 16, in <module>
    from settings import *
ImportError: No module named settings

Setup was done by following instructions in cloud README.py. @matt-9-johnson was also able to reproduce this error.

Running Ubuntu 16.04, from commit 3dfb55690dfc8854e3838c787ec94b0230788615

**Comment by 9muir** [comment]
File got lost in transition to a public repo, reinstated it via direct push (https://github.com/facebookincubator/CommunityCellularManager/commit/17876383cd8998e0b4bd31c70a9407acb791e4b6)
