### ISSUE TITLE
python-ESL module is not automatically installed

### ISSUE THREAD

**Issue by eprueves** [facebookincubator/CommunityCellularManager#14]
Missing python-ESL module, [error](https://gist.github.com/eprueves/b1c808cf1cd2d28e01f04d98375da1db#file-provisioning-error-L11) occurs when attempting to provision phones. 
Workaround for the meantime is to manually install this.

**Comment by 9muir** [comment]
Working on a patch to automatically build this module, stay tuned. Thanks for reporting.

**Comment by kkroo** [comment]
Resolved in #28
