### ISSUE TITLE
There are no pictures anymore

### ISSUE THREAD

**Issue by kheimerl** [facebookincubator/CommunityCellularManager#16]
Static directory seems to have gone missing.

**Comment by 9muir** [comment]
yes, looks like it doesn't get copied by our ShipIt script, but I'm not sure why (we don't exclude it, so it might be a Facebook default). Will fix

**Comment by 9muir** [comment]
`[endagaweb/]static` is listed in https://github.com/facebookincubator/CommunityCellularManager/blob/master/cloud/.gitignore, which I think is why ShipIt ignores it.

**Comment by 9muir** [comment]
Leaving this open until we fix `.gitignore`

**Comment by 9muir** [comment]
Resolved by https://github.com/facebookincubator/CommunityCellularManager/commit/9e5415db9a3692f9b1691a4a0c95b7bd43c29fff
