### ISSUE TITLE
nginx config incorrect

### ISSUE THREAD

**Issue by kheimerl** [facebookincubator/CommunityCellularManager#17]
As per https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#taxing-rewrites

nginx config ssl redirect should be:

    # Force HTTPS
    if ($http_x_forwarded_proto != "https") {
      return 301 https://$host$request_uri;
    }

**Comment by 9muir** [comment]
do you want to just make that a PR? Was that the cause of the double parameter in the query string?

**Comment by kheimerl** [comment]
I can make one eventually but i'm in the midst of the whole thing. This was the cause of the double param.

**Comment by 9muir** [comment]
Closing, will accept PR once it's available.
