### ISSUE TITLE
CCM client not registering with cloud instances

### ISSUE THREAD

**Issue by mferland** [facebookincubator/CommunityCellularManager#29]
I've followed both cloud and client READMEs and so far everything seems to be running OK. The _only_ issue which remains is that I cannot get the client to send status updates to the cloud.

Looking at the /var/log/endagad logs I see things like:
~~~~
Unable to verify client cert against CA bundle
~~~~

Similarly in /var/log/endaga:
~~~~
[CRITICAL] endaga: system_utilities.py:260:verify_cert: Unable to verify client cert against CA bundle:#012/etc/openvpn/endaga-client.crt
~~~~

What did I do wrong?

Any help would be appreciated!

**Comment by kheimerl** [comment]
Did you update the bundle to the one you generated? The one in the package
is for our cloud. To check, find the bundle in your client build directory
and diff it with the one in /etc/endaga/

**Comment by 9muir** [comment]
The error indicates that the root CA that was used to sign the client certificate is not the same as the root cert installed in the client. You need to ensure that `etage-bundle.crt` in the certifier VM is the same as `etage-bundle` in the client (in `/etc/openvpn`).

**Comment by mferland** [comment]
Ah! I did forgot to update the bundle. Thanks for pointing that out.
