### ISSUE TITLE
setuptools missing from python3

### ISSUE THREAD

**Issue by kheimerl** [facebookincubator/CommunityCellularManager#46]
building new openbts VM:

ImportError: No module named 'setuptools'

**Comment by kheimerl** [comment]
apt-get install python3-setuptools fixed it, probably just needs to be added to ansible

**Comment by kheimerl** [comment]
Looking at it, the real issue is that pip3 is version 1.5 in ubuntu 14. I'm working on a patch but will probably leave that.

**Comment by 9muir** [comment]
I think we've basically deprecated any use of the OpenBTS-specific stuff, but will gladly accept PRs if people are still using it.
