### ISSUE TITLE
missing libssl-dev on omsocom provisioning

### ISSUE THREAD

**Issue by kheimerl** [facebookincubator/CommunityCellularManager#48]
This ticket: https://github.com/wantedly/step-pretty-slack-notify/issues/34

Shows the error. Was fixed by installing libssl-dev, needs to be added to ansible.

**Comment by 9muir** [comment]
I think this is resolved by #51 and #53, right?

**Comment by kheimerl** [comment]
Yes that looks right

mobile

**Comment by 9muir** [comment]
okay, re-open if not resolved.
