### ISSUE TITLE
sms_credit_transfer.py allows credit transfer to own account

### ISSUE THREAD

**Issue by eprueves** [facebookincubator/CommunityCellularManager#72]
If a user tries to transfer credit to his own account, the transaction is allowed. Though not exactly a bug, it makes more sense to disallow transferring credits to oneself. 

I've created a branch fixing this in our fork. If acceptable, a PR can be created.  
https://github.com/pcarivbts/CommunityCellularManager/commit/47171b9d025fc799281f71aa37b9a04e922ade6a

**Comment by 9muir** [comment]
I agree, that seems like something that should be prohibited. Please create the PR.

**Comment by eprueves** [comment]
commit 7085839659d99cb27316d19a01908fdda87d3193 closes this issue
