### ISSUE TITLE
client: missing FS global variable 'smqueue_profile'

### ISSUE THREAD

**Issue by eprueves** [facebookincubator/CommunityCellularManager#9]
In /core/sms/freeswitch/_openbts.py, send() and send_direct() looks for the "smqueue_profile" global variable:
`to_full = str(freeswitch.getGlobalVariable("smqueue_profile") +
                          "/sip:smsc@" + sip_my_ip + ":" + sip_my_port)`

But this is now missing in /etc/freeswitch/vars.xml when the openbts/osmocom profiles were refactored to internal. This causes "VBTS_Send_SMS_Direct" to fail with the ff error:

`2016-11-10 06:06:17.337288 [ERR] mod_python.c:164 Python Error by calling script "VBTS_Send_SMS_Direct": <type 'exceptions.TypeError'>
Message: unsupported operand type(s) for +: 'NoneType' and 'str'
Exception: None`

Fix would be to add this line in vars.xml and restart fs.
`<X-PRE-PROCESS cmd="set" data="smqueue_profile=internal"/>`

Tested on openbts dev-client using 44c7827.

**Comment by 9muir** [comment]
Thanks for catching this, we also noticed it internally and will have that fix added shortly.

**Comment by 9muir** [comment]
Resolved by https://github.com/facebookincubator/CommunityCellularManager/commit/5415888bde6ae27c323f73ba67c05eb53f9b869f
