### ISSUE TITLE
Installs with new versions of fabric fail

### ISSUE THREAD

**Issue by matt9j** [facebookincubator/CommunityCellularManager#98]
It appears that fabric is moving on to a new API version, and new versions of fabric are now being deployed via pip. https://github.com/uw-ictd/CommunityCellularManager/issues/16

**Comment by 9muir** [comment]
yeah, it looks Fabric 2.0, while being pretty cool in various ways, is not backwards compatible. Since it's unlikely that the fabfile will get updated in the near future, I think your proposed workaround is the best 'solution':

`pip install "fabric<2.0.0"`
